<?php

/**
 * @file
 * Defines the install/uninstall hooks for this module.
 */

/**
 * Implements hooks_requirements().
 */
function islandora_internet_archive_bookreader_requirements($phase) {
  $requirements = array();
  $t = get_t();

  if (!function_exists('libraries_get_libraries')) {
    module_enable(array('libraries'));
  }
  if (!in_array('colorbox', array_keys(libraries_get_libraries()))) {
    $readme_link = l($t('README'), drupal_get_path('module', 'islandora_internet_archive_bookreader') . '/README.md');
     $requirements['colorbox'] = array(
       'title' => $t('Colorbox library'),
       'description' => $t('Colorbox library missing; please consult the !readme for installation instructions.', array('!readme' => $readme_link)),
       'severity' => REQUIREMENT_ERROR,
     );
  }
  return $requirements;
}

/**
 * Implements hook_uninstall().
 */
function islandora_internet_archive_bookreader_uninstall() {
  $variables = array(
    'islandora_internet_archive_bookreader_djatoka_url',
    'islandora_internet_archive_bookreader_compression',
    'islandora_internet_archive_bookreader_ocr_field',
    'islandora_internet_archive_bookreader_ocr_filter_field',
    'islandora_internet_archive_bookreader_solr_result_count',
    'islandora_internet_archive_bookreader_sequence_number',
    'islandora_internet_archive_bookreader_overlay_opacity',
    'islandora_internet_archive_bookreader_default_page_view',
  );
  // Delete the Drupal variables defined by this module.
  array_walk($variables, 'variable_del');
}
